### ISSUE TITLE
clientId and clientSecret

### ISSUE THREAD

**Issue by luthv** [bukalapak/bukalapak.js#3]
Hi,

I'm trying to use bukalapak API from my application.

Where do we get the clientId and clientSecret? Also is there any official documentation for the latest API version?

**Comment by xinuc** [comment]
Hi Luthfi,

this client library is for our new (and unreleased) API version.
We currently don't have any public documentation.

We plan to publish it, though, as soon as it's ready.

Thanks.

**Comment by luthv** [comment]
Makasih reply-nya.

Boleh dapet early access nggak? sama ada rencana buat sandbox-nya nggak supaya kita bisa coba2 tanpa mengganggu production site-nya?
